### ISSUE TITLE
Change animal list element shown date based on state

### ISSUE THREAD

**Issue by counter567** [counter567/shelterapp#12]
One shelter requested to change the displayed date according to it's state:

Deceased: dateOfDeath
Mediated: dateOfLeave
Other: dateOfAdmission

**Comment by Bellian** [comment]
@Sevenhero

**Comment by Sevenhero** [comment]
@counter567 what should we show for other? Since this doesn't have a meaning I would leave it

**Comment by Bellian** [comment]
Fixed it. was a minor thing.
