### ISSUE TITLE
"Vermisst" and "vermittelt" Missing animals

### ISSUE THREAD

**Issue by Sean-R-94** [counter567/shelterapp#27]
Animals wearing this tag in Cloud4Pets don't show them in the new system. Only shows newly added (in WP) missing and adopted animals.

**Comment by Bellian** [comment]
Do you have a link for me there? please try to provide links if possible.

**Comment by Sean-R-94** [comment]
Not all Animals, which were previously missing or adopted in cloud4pets are showing in the new system. There are no issues with newly added missing or adopted but old animals do not seem to be able to appear. 

https://tierheim-neuwied.de/tiere/#shelterapp_animal_type=56,60,59,52,53,54,57,55,58,51&meta_status=NEW,SEARCHING,REQUEST_STOP,EMERGENCY,RESERVED,FINAL_CARE,COURT_OF_GRACE&meta_missing=true&meta_order=DESC&meta_orderby=dateOfAdmission

https://katzenschutzfreunde.de/vermisst/

https://gemeinsamfuertiere.de/notfall-tiere/#shelterapp_animal_type=475,476,477,478&meta_status=EMERGENCY,FINAL_CARE&meta_missing=true&meta_order=DESC&meta_orderby=dateOfAdmission

example links for missing animals for now.

**Comment by Bellian** [comment]
These animals that are missing do not hve a animal type. the filter block is told that it should only show certain animal types. so these are not shown.
