### ISSUE TITLE
Odd special case Remagen

### ISSUE THREAD

**Issue by Sean-R-94** [counter567/shelterapp#29]
There seems to be some kind of label or tag or whatever missing for remagen. 

They not only had "Adopted" but also "Grüße von den Tieren" seperately. 

https://www.tierheim-remagen.de/grusze-von-tieren/

Animals shown under this Link were adopted and had new images of them in their new home (from how much I could understand)

**Comment by Bellian** [comment]
It is not possible to get animals that have newer media than the release date.
Would be muuuch easier to link to the animals in a galery with the new images.

**Comment by counter567** [comment]
Will be covered by [https://github.com/counter567/shelterapp/issues/33](this issue)
