### ISSUE TITLE
Issue causing critical error

### ISSUE THREAD

**Issue by Sean-R-94** [counter567/shelterapp#34]
![image](https://github.com/user-attachments/assets/c4516c9a-30fd-49c5-aeb9-9214bc1bfe57)

This Mail came in this morning. 

Also I get a critical error anytime I delete an animal - it still works after going back to dashboard via URL.

**Comment by counter567** [comment]
Should be fixed by https://github.com/counter567/shelterapp/commit/2d171ecf03c2f7e4c4bac60e6ad462e3ccddb730
