### ISSUE TITLE
"Fundtier"-Tag is not always shown

### ISSUE THREAD

**Issue by counter567** [counter567/shelterapp#8]
The tag behaves weird. Sometimes it is shown when wasFound is true and sometimes not.

**Comment by Bellian** [comment]
@Sevenhero

**Comment by Sevenhero** [comment]
@Bellian was bekommen wir denn vom Backend? Bei missing klappt es ja. Als ich letztens mal rein geschaut habe stand da '1' oder '0' manchmal '' was ist empty string?

**Comment by Sevenhero** [comment]
was ist jetzt was ? @Bellian 
![image](https://github.com/user-attachments/assets/60240997-2970-416e-8eb1-09777e13232b)
